### ISSUE TITLE
Example not working with Ember 2.13

### ISSUE THREAD

**Issue by BryanHunt** [LocusEnergy/ember-sparkles#61]
I'm trying to get your example line chart working and I'm using Ember 2.13.  I think I figured out all of the dependencies, but now I'm getting this exception:

```
Error: let not found, and the catch-all block handler didn't handle it
    at Object.debugAssert [as assert] (http://localhost:4200/assets/vendor.js:16550:19)
    at Blocks.compile (http://localhost:4200/assets/vendor.js:16254:241)
    at http://localhost:4200/assets/vendor.js:16249:3224
    at Compilers.compile (http://localhost:4200/assets/vendor.js:16249:531)
    at compileStatement (http://localhost:4200/assets/vendor.js:16248:8728)
    at http://localhost:4200/assets/vendor.js:16248:727
    at Array.forEach (native)
    at WrappedBuilder.compile (http://localhost:4200/assets/vendor.js:16248:692)
    at ComponentLayoutBuilder.compile (http://localhost:4200/assets/vendor.js:16221:715)
    at Object.compileLayout (http://localhost:4200/assets/vendor.js:16221:280)
defaultDispatch @ ember.debug.js:19822
dispatchError @ ember.debug.js:19801
invokeWithOnError @ ember.debug.js:2204
flush @ ember.debug.js:2260
flush @ ember.debug.js:2384
end @ ember.debug.js:2454
run @ ember.debug.js:2568
join @ ember.debug.js:2599
run.join @ ember.debug.js:24497
(anonymous) @ ember.debug.js:24560
mightThrow @ jquery.js:3583
process @ jquery.js:3651
```

**Comment by ghost** [comment]
Thanks for reporting this, @BryanHunt. I am pretty busy this week but I will be able to take a look over the weekend if not before.

**Comment by BryanHunt** [comment]
Ping

**Comment by ghost** [comment]
Hi - I'm sorry for the delay, I'll take a look at this today.

**Comment by ghost** [comment]
@BryanHunt can you please share your sample app with me?

**Comment by yarigpopov** [comment]
@BryanHunt have you installed ember-let?

**Comment by BryanHunt** [comment]
Installing ember-let fixes the problem.

**Comment by ghost** [comment]
@chilicoder thank you for mentioning this. It sounds like it provides a fix! I'm sorry I haven't been active on this project lately, I'm glad that you were able to get this working. I will try updating the dependency structure so that the external library is not required.
